modLoader="javafml"
loaderVersion="[4,)"
license="CC0-1.0"

[[mods]]
modId="create"
version="${version}"
displayName="Create"
description='''
Create port for Minecraft 26.2 and NeoForge.
'''

[[mixins]]
config="create.mixins.json"

[[mixins]]
config="create.client.mixins.json"

[[dependencies.create]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.create]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="BOTH"
